import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {

  return (
    <html lang="pt-br" className={`${poppins.className}`}>
      <body>
        <div>
          {children}
          <Header />
        </div>
      </body>
    </html>
  );
}
